"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](color_1)\
$os\
$time\
[](bg:color_3 fg:color_1)\
$directory\
[](fg:color_3 bg:color_5)\
$git_branch\
$git_status\
[](fg:color_5 bg:color_6)\
$c\
$cpp\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
[](fg:color_6 bg:color_7)\
$docker_context\
$conda\
$pixi\
[](fg:color_7 bg:color_8)\
[ ](fg:color_8)\
$line_break$character"""

palette = 'mono_gradient'

[palettes.mono_gradient]
color_fg = '#e6edf3'
color_1 = '#5a7bb4'
color_2 = '#4c6aa3'
color_3 = '#3f5a92'
color_4 = '#354b80'
color_5 = '#2f4775'
color_6 = '#2b3f68'
color_7 = '#253050'
color_8 = '#20283f'

[os]
disabled = false
style = "bg:color_1 fg:color_fg"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
AOSC = ""
Arch = "󰣇"
Artix = "󰣇"
EndeavourOS = ""
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"
Pop = ""

[directory]
style = "fg:color_fg bg:color_3"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = ""
style = "bg:color_5"
format = '[[ $symbol $branch ](fg:color_fg bg:color_5)]($style)'

[git_status]
style = "bg:color_5"
format = '[[($all_status$ahead_behind )](fg:color_fg bg:color_5)]($style)'

[nodejs]
symbol = ""
style = "bg:color_6"
format = '[[ $symbol( $version) ](fg:color_fg bg:color_6)]($style)'

[c]
symbol = " "
style = "bg:color_6"
format = '[[ $symbol( $version) ](fg:color_fg bg:color_6)]($style)'

[cpp]
symbol = " "
style = "bg:color_6"
format = '[[ $symbol( $version) ](fg:color_fg bg:color_6)]($style)'

[rust]
symbol = ""
style = "bg:color_6"
format = '[[ $symbol( $version) ](fg:color_fg bg:color_6)]($style)'

[golang]
symbol = ""
style = "bg:color_6"
format = '[[ $symbol( $version) ](fg:color_fg bg:color_6)]($style)'

[php]
symbol = ""
style = "bg:color_6"
format = '[[ $symbol( $version) ](fg:color_fg bg:color_6)]($style)'

[java]
symbol = ""
style = "bg:color_6"
format = '[[ $symbol( $version) ](fg:color_fg bg:color_6)]($style)'

[kotlin]
symbol = ""
style = "bg:color_6"
format = '[[ $symbol( $version) ](fg:color_fg bg:color_6)]($style)'

[haskell]
symbol = ""
style = "bg:color_6"
format = '[[ $symbol( $version) ](fg:color_fg bg:color_6)]($style)'

[python]
symbol = ""
style = "bg:color_6"
format = '[[ $symbol( $version) ](fg:color_fg bg:color_6)]($style)'

[docker_context]
symbol = ""
style = "bg:color_7"
format = '[[ $symbol( $context) ](fg:color_fg bg:color_7)]($style)'

[conda]
style = "bg:color_7"
format = '[[ $symbol( $environment) ](fg:color_fg bg:color_7)]($style)'

[pixi]
style = "bg:color_7"
format = '[[ $symbol( $version)( $environment) ](fg:color_fg bg:color_7)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:color_1 fg:color_fg"
format = '[[ $time ](fg:color_fg bg:color_1)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[](bold fg:color_6)'
error_symbol = '[](bold fg:color_4)'
vimcmd_symbol = '[](bold fg:color_6)'
vimcmd_replace_one_symbol = '[](bold fg:color_2)'
vimcmd_replace_symbol = '[](bold fg:color_2)'
vimcmd_visual_symbol = '[](bold fg:color_3)'
